---
- name: Check SSH connection
  ping:
  register: ping_result
  failed_when: ping_result.ping != 'pong'

- name: Log SSH connection status
  debug:
    msg: "SSH connection successful to {{ inventory_hostname }}"
  when: ping_result.ping == 'pong'

- name: Check if NFS is installed
  package:
    name: "{{ item }}"
    state: present
  loop:
    - nfs-kernel-server
    - nfs-common
  register: nfs_install
  ignore_errors: yes

- name: Log NFS installation status
  debug:
    msg: "NFS packages installation status: {{ nfs_install }}"

- name: Get NFS version
  shell: rpcinfo -p | grep nfs
  register: nfs_version
  ignore_errors: yes

- name: Log NFS version
  debug:
    msg: "NFS version information: {{ nfs_version.stdout_lines }}"
  when: nfs_version.rc == 0 