version: '3.8'

services:
  backend:
    build: ./backend
    container_name: disk-manager-backend
    restart: unless-stopped
    volumes:
      - /mnt/disk_sda1:/mnt/disk_sda1:ro
      - /mnt/disk_sdb1:/mnt/disk_sdb1:ro
      - /mnt/disk_sdb5:/mnt/disk_sdb5:ro
      - ./backend/logs:/app/logs
    ports:
      - "6005:6005"
    environment:
      - NODE_ENV=production
      - PORT=6005
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: disk-manager-frontend
    restart: unless-stopped
    ports:
      - "6001:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge