---
- name: Подготовка SSH-ключей
  hosts: debian_servers
  become: yes
  gather_facts: false
  tasks:
    - name: Создание SSH-ключа для пользователя
      user:
        name: debianuser
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: /home/debianuser/.ssh/id_rsa

    - name: Установка authorized_keys
      authorized_key:
        user: debianuser
        state: present
        key: "{{ lookup('file', '/home/debianuser/.ssh/id_rsa.pub') }}"

- name: Настройка Debian сервера (Agger)
  hosts: debian_servers
  become: true
  gather_facts: false

  pre_tasks:
    - name: Установка sudo
      raw: apt-get update && apt-get install -y sudo python3
      register: sudo_install
      changed_when: "'0 upgraded, 0 newly installed' not in sudo_install.stdout"

    - name: Настройка sudo для текущего пользователя
      raw: echo "debianuser ALL=(ALL:ALL) NOPASSWD:ALL" | tee /etc/sudoers.d/debianuser
      register: sudo_config
      changed_when: sudo_config.rc == 0

    - name: Сбор фактов после установки необходимых пакетов
      setup:

  roles:
    - common            # Базовые пакеты
    - network           # Настройка сети
    - users             # Настройка пользователей
    - samba             # Настройка Samba и монтирование дисков
    - sync              # Настройка синхронизации между серверами