# /etc/exports: файл конфигурации NFS экспорта
#
# Формат:
# /путь/к/каталогу  IP_или_сеть(опции)
# Пример: /mnt/disk_sda1  192.168.0.0/24(rw,sync,no_subtree_check)

# Экспорты для всех дисков с оптимизированными параметрами для быстрой передачи файлов
/mnt/disk_sda1  192.168.0.0/24(rw,async,no_subtree_check,no_root_squash,no_wdelay)
/mnt/disk_sdb1  192.168.0.0/24(rw,async,no_subtree_check,no_root_squash,no_wdelay)
/mnt/disk_sdb5  192.168.0.0/24(rw,async,no_subtree_check,no_root_squash,no_wdelay)
/mnt/disk_sdc1  192.168.0.0/24(rw,async,no_subtree_check,no_root_squash,no_wdelay)
/mnt/disk_sdd1  192.168.0.0/24(rw,async,no_subtree_check,no_root_squash,no_wdelay) 