---
- name: Настройка NFS сервера
  hosts: agger
  become: true
  roles:
    - common
    - nfs
    - samba
  
- name: Настройка клиента NFS
  hosts: apper
  become: true
  roles:
    - common
    - sync 
    - backup 