---
# roles/users/tasks/main.yml
- name: Создание пользователя agger
  user:
    name: agger
    password: "{{ '2864' | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Настройка sudo для нового пользователя
  copy:
    content: "agger ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: /etc/sudoers.d/agger
    mode: '0440'

- name: Создание директории .ssh
  file:
    path: /home/agger/.ssh
    state: directory
    owner: agger
    group: agger
    mode: '0700'

- name: Генерация SSH ключа для пользователя agger
  user:
    name: agger
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa

- name: Получение публичного ключа
  slurp:
    src: /home/agger/.ssh/id_rsa.pub
  register: agger_pubkey