#!/bin/bash

# Скрипт для полного исправления конфигурации NFS

# Цвета для вывода
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== ПОЛНОЕ ИСПРАВЛЕНИЕ КОНФИГУРАЦИИ NFS ===${NC}"

# Проверка прав root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Ошибка: Требуются права администратора${NC}"
  echo "Запустите: sudo $0"
  exit 1
fi

# Определение пути к каталогу скрипта
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
INVENTORY_FILE="$SCRIPT_DIR/inventory"

if [ ! -f "$INVENTORY_FILE" ]; then
  echo -e "${RED}Ошибка: Файл inventory не найден: $INVENTORY_FILE${NC}"
  echo "Запускайте скрипт из каталога ansible-setup или укажите полный путь"
  
  # Пробуем найти файл inventory в других местах
  POSSIBLE_INVENTORY=$(find ~/iqbanana_space_disk -name inventory -type f 2>/dev/null | head -1)
  if [ -n "$POSSIBLE_INVENTORY" ]; then
    echo -e "${YELLOW}Найден файл inventory: $POSSIBLE_INVENTORY${NC}"
    echo "Использовать его? (y/n)"
    read use_found
    if [ "$use_found" = "y" ]; then
      INVENTORY_FILE="$POSSIBLE_INVENTORY"
    else
      exit 1
    fi
  else
    exit 1
  fi
fi

echo "Используется файл inventory: $INVENTORY_FILE"

# Получаем данные сервера и клиента
SERVER_IP=$(grep -o "^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+" "$INVENTORY_FILE" | head -1)
SERVER_USER=$(grep -o "ansible_user=\w\+" "$INVENTORY_FILE" | head -1 | cut -d= -f2)
SERVER_PASS=$(grep -o "ansible_ssh_pass=[^ ]\+" "$INVENTORY_FILE" | head -1 | cut -d= -f2)
CLIENT_IP=$(grep -o "^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+" "$INVENTORY_FILE" | tail -1)

if [ -z "$SERVER_IP" ] || [ -z "$SERVER_USER" ]; then
  echo -e "${RED}Ошибка: Не удалось получить данные о сервере из файла inventory${NC}"
  exit 1
fi

echo "Сервер NFS: $SERVER_IP (пользователь: $SERVER_USER)"
echo "Клиент NFS: $CLIENT_IP"

echo -e "\n${YELLOW}[1/6] Остановка NFS клиента и размонтирование...${NC}"
systemctl stop nfs-common
umount -f -l -a -t nfs 2>/dev/null || true
echo "Клиент остановлен, все NFS размонтированы"

echo -e "\n${YELLOW}[2/6] Остановка и сброс NFS сервера...${NC}"
# Команды для остановки и сброса NFS сервера
SERVER_RESET_CMD="sudo systemctl stop nfs-kernel-server;
                 sudo exportfs -ua;
                 sudo rm -f /etc/exports;
                 sudo rm -f /var/lib/nfs/etab /var/lib/nfs/rmtab;
                 sudo touch /etc/exports;
                 echo 'Сервер NFS остановлен и сброшен'"

# Выполнение на сервере
if [ -n "$SERVER_PASS" ]; then
  sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "$SERVER_RESET_CMD"
else
  ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "$SERVER_RESET_CMD"
fi

echo -e "\n${YELLOW}[3/6] Создание правильной конфигурации NFS...${NC}"
# Формируем правильную конфигурацию exports
NFS_EXPORTS="# NFS exports configuration
# Generated by fix script on $(date)

/mnt/storage/sda $CLIENT_IP(rw,sync,no_subtree_check,no_root_squash,insecure)
/mnt/storage/sdb $CLIENT_IP(rw,sync,no_subtree_check,no_root_squash,insecure)"

# Применяем на сервере
if [ -n "$SERVER_PASS" ]; then
  echo "$NFS_EXPORTS" | sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo tee /etc/exports > /dev/null"
else
  echo "$NFS_EXPORTS" | ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "sudo tee /etc/exports > /dev/null"
fi

echo -e "\n${YELLOW}[4/6] Проверка конфигурации, запуск и перезагрузка NFS сервера...${NC}"
# Перезапуск NFS сервера
SERVER_START_CMD="sudo cat /etc/exports;
                 sudo exportfs -ra;
                 sudo systemctl restart nfs-kernel-server;
                 sudo systemctl enable nfs-kernel-server;
                 sudo exportfs -v;
                 echo 'NFS сервер перезапущен'"

# Выполнение на сервере
if [ -n "$SERVER_PASS" ]; then
  sshpass -p "$SERVER_PASS" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "$SERVER_START_CMD"
else
  ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "$SERVER_START_CMD"
fi

echo -e "\n${YELLOW}[5/6] Перезапуск клиента NFS и монтирование...${NC}"
# Перезапуск NFS клиента
systemctl restart nfs-common

# Убедитесь, что каталоги существуют
mkdir -p /mnt/storage/sda /mnt/storage/sdb

# Ручное монтирование
echo "Монтирование /mnt/storage/sda..."
mount -t nfs $SERVER_IP:/mnt/storage/sda /mnt/storage/sda -o rw,soft,timeo=10,retrans=2,noatime
echo "Монтирование /mnt/storage/sdb..."
mount -t nfs $SERVER_IP:/mnt/storage/sdb /mnt/storage/sdb -o rw,soft,timeo=10,retrans=2,noatime

echo -e "\n${YELLOW}[6/6] Проверка результатов монтирования...${NC}"
# Проверка смонтированных NFS
mount | grep nfs || echo "Предупреждение: NFS не смонтированы"

# Проверка доступа на запись
echo "Тестирование доступа на запись..."
touch /mnt/storage/sda/test_file.txt && echo "Успешная запись в /mnt/storage/sda" || echo "Ошибка записи в /mnt/storage/sda"
touch /mnt/storage/sdb/test_file.txt && echo "Успешная запись в /mnt/storage/sdb" || echo "Ошибка записи в /mnt/storage/sdb"

# Очистка тестовых файлов
rm -f /mnt/storage/sda/test_file.txt /mnt/storage/sdb/test_file.txt

echo -e "\n${GREEN}Операция завершена!${NC}"
echo "Диски NFS должны быть доступны в /mnt/storage/"
df -h | grep nfs