---
# roles/network/tasks/main.yml
- name: Установка необходимых пакетов для сети
  apt:
    name:
      - net-tools
      - iproute2
      - ifupdown
      - netplan.io
    state: present

- name: Конфигурация статического IP через netplan
  template:
    src: netplan.j2
    dest: /etc/netplan/01-netcfg.yaml
  register: netplan_config

- name: Применение конфигурации netplan
  command: netplan apply
  when: netplan_config.changed